all: gtushell

gtushell:
	gcc -std=gnu99 gtushell.c -o gtushell
	gcc lsf.c -o lsf
	gcc cat.c -o cat
	gcc bunedu.c -o bunedu
	gcc pwd.c -o pwd
	gcc wc.c -o wc

clean:
	rm -f *.o gtushell pwd cat bunedu lsf wc

